# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b21009a6b8a1792e7edff8d1de3021da747a9ed00a2af9b095d79d5acdc039100bda3b90dab297e46f598715648fdddfe923df0820000f3b99aba5b1818853

test:
  secret_key_base: 3e1b764e3ce3b8573a16ddd0009af5a4b25a8a0b780108a55d22b642d0da62b2c64ce6a19e261c85f237f5c44403e6171b7e78426ca4450d16dc5c39ca350578

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
